---
apt_sources_replace: true

apt_sources_lists_default:
    # Debian
    -
        comment: Official repositories
        file: /etc/apt/sources.list
        distrib: Debian
        repositories:
            -
                comment: 'Main repositories'
                enabled: true
                src_enabled: true
                url: 'http://httpredir.debian.org/debian/'
                packages: ['main','contrib','non-free']
                section:  "{{ ansible_distribution_release }}"
            -
                comment: 'Updates repositories'
                enabled: true
                src_enabled: true
                url: 'http://httpredir.debian.org/debian/'
                packages: ['main','contrib','non-free']
                section:  "{{ ansible_distribution_release }}-updates"
            -
                comment: 'Security Updates repositories'
                enabled: true
                src_enabled: true
                url: 'http://security.debian.org/'
                packages: ['main','contrib','non-free']
                section:  "{{ ansible_distribution_release }}/updates"
            -
                comment: 'Backports repositories'
                enabled: true
                src_enabled: true
                url: 'http://httpredir.debian.org/debian/'
                packages: ['main','contrib','non-free']
                section:  "{{ ansible_distribution_release }}-backports"

    # Ubuntu
    -
        comment: Official repositories
        file: /etc/apt/sources.list
        distrib: Ubuntu
        repositories:
            -
                comment: 'Main repositories'
                enabled: true
                src_enabled: true
                url: 'http://fr.archive.ubuntu.com/ubuntu/'
                packages: ['main', 'restricted', 'universe', 'multiverse']
                section:  "{{ ansible_distribution_release }}"
            -
                comment: 'Update repositories'
                enabled: true
                src_enabled: true
                url: 'http://fr.archive.ubuntu.com/ubuntu/'
                packages: ['main', 'restricted', 'universe', 'multiverse']
                section:  "{{ ansible_distribution_release }}-updates"
            -
                comment: 'Security Update repositories'
                enabled: true
                src_enabled: true
                url: 'http://security.ubuntu.com/ubuntu'
                packages: ['main', 'restricted', 'universe', 'multiverse']
                section:  "{{ ansible_distribution_release }}-security"
            -
                comment: 'Partner repositories'
                enabled: true
                src_enabled: true
                url: 'http://archive.canonical.com/ubuntu'
                packages: ['partner']
                section:  "{{ ansible_distribution_release }}"
            -
                comment: 'Backports repositories'
                enabled: true
                src_enabled: true
                url: 'http://fr.archive.ubuntu.com/ubuntu'
                packages: ['main', 'restricted', 'universe', 'multiverse']
                section:  "{{ ansible_distribution_release }}-backports"

apt_sources_lists_extra: []
    # -
    #     comment:
    #     file: /etc/apt/sources.list.d/<file>.list
    #     distrib: Debian
    #     repositories:
    #         -
    #             comment:
    #             enabled: true
    #             src_enabled: false
    #             url:
    #             packages: []
    #             section:  # default ansible_distribution_release
    #             section_prefix:
    #             section_suffix:
    #             archs: []
    #             key_server:
    #             key_url:
    #             key_id:

apt_update_cache_valid_time: 3600
apt_upgrade_type: safe
apt_upgrade: false

# list of default packages to install
apt_default_packages :
  - vim
  - vim-doc
  - trash-cli
  - tree
  - mc
  - ack-grep
  - manpages-fr
  - manpages-fr-dev
  - manpages-fr-extra
  - git
  - git-extras
  - git-doc
  - bash-completion
  - build-essential
  - openssh-server
  - openssh-client
  - openssh-blacklist
  - openssh-blacklist-extra
  - acl
  - nano
  - openssl
  - openssl-blacklist
  - openssl-blacklist-extra
  - ncftp
  - lftp
  - rsync
  - p7zip
  - p7zip-full
  - p7zip-rar
  - lzma
  - unrar
  - rar
  - screen
  - tmux
  - tofrodos
  - diffutils
  - colordiff
  - dos2unix
  - patch
  - clamav
  - clamav-freshclam

# list of extra packages to install
apt_extra_packages: []

# list of packages to remove
apt_remove_packages: []
